-- ============================================================================
-- VILOCCI / VELOCCI — Product colors backfill for the PRODUCTION Supabase
-- Project ref: zbqnkebsmhhemknpazme  (instance: vilocciii3bro.vercel.app)
-- Generated from data/velocci-db.json + supabase/migrations/004_product_colors.sql
--
-- WHAT THIS TOUCHES — nothing else:
--   * migration 004 DDL: adds products.colors + order_items.color (idempotent)
--   * UPDATE products SET colors ONLY (117 products, palettes from the repo)
--   * merges 4 dictionary keys (color/colors/select_color/color_required)
--     into settings.languages via jsonb_set — every other key untouched
-- Never deletes, never truncates, safe to re-run.
-- ============================================================================

begin;

-- ---- migration 004 (verbatim) ---------------------------------------------
-- ============================================================================
-- 004_product_colors.sql — per-product color variants
-- ----------------------------------------------------------------------------
-- Applied on top of supabase-schema.sql (001), 002_cms_core.sql (002) and
-- 003_customize.sql (003).
--
-- Gives EVERY product its own ordered list of color variants, managed in
-- Admin → Products → Colors:
--
--   products.colors jsonb — [ { id, name_en, name_ar, hex, enabled }, … ]
--     * array position IS the display order (admins reorder colors)
--     * enabled = false keeps the color in admin without showing it in the
--       storefront
--     * the SAME column feeds the storefront, cart/checkout validation,
--       orders and the Customize flow — there is no second color system
--
--   order_items.color jsonb — snapshot of the color the customer picked for
--     that line: { id, name_en, name_ar, hex }. A snapshot on purpose, so an
--     order keeps showing the chosen color even if the catalog color is later
--     renamed, disabled or deleted. (orders.items jsonb already carries the
--     same payload for legacy rows.)
--
-- SAFETY RULES (same as 002 / 003 — this file is safe to run again and again):
--   1. Only ADD COLUMN IF NOT EXISTS / defaults. Never a DROP, never a DELETE,
--      never a TRUNCATE: no existing row is touched.
--   2. Existing products get '[]' — the storefront shows no color selector for
--      them until the admin adds colors, exactly like today.
-- ============================================================================

-- 1. Product color variants --------------------------------------------------
alter table public.products add column if not exists colors jsonb default '[]'::jsonb;

-- 2. The color chosen by the customer on each order line ---------------------
alter table public.order_items add column if not exists color jsonb;

-- ---- product color palettes (colors column only) --------------------------
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_mercedes-benz_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_mercedes-benz_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_mercedes-benz_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_mercedes-benz_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_bmw_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_bmw_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_bmw_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_bmw_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_audi_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_audi_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_audi_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_audi_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_porsche_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_porsche_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_porsche_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_porsche_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_land-rover_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_land-rover_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_land-rover_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_land-rover_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_range-rover_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_range-rover_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_range-rover_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_range-rover_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_lexus_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_lexus_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_lexus_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_lexus_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_toyota_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_toyota_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_toyota_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_toyota_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_jeep_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_jeep_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_jeep_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_jeep_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_volkswagen_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_volkswagen_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_volkswagen_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_volkswagen_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_volvo_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_volvo_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_volvo_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_volvo_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_ford_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_ford_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_ford_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_ford_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_honda_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_honda_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_honda_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_honda_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_hyundai_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_hyundai_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_hyundai_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_hyundai_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_kia_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_kia_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_kia_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_kia_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_tesla_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_tesla_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_tesla_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_tesla_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_maserati_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_maserati_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_maserati_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_maserati_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_ferrari_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_ferrari_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_ferrari_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_ferrari_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_lamborghini_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_lamborghini_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_lamborghini_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_lamborghini_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_bentley_case_carbon';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_bentley_case_leather';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_bentley_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_bentley_medal';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_tesla_case_premium';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_mg_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_mg_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_mg_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_mg_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_peugeot_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_peugeot_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_peugeot_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_peugeot_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_byd_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_byd_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_byd_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_byd_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_gac_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_gac_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_gac_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_gac_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_jetour_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_jetour_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_jetour_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_jetour_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_citroen_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_citroen_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_citroen_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_citroen_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_haval_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_haval_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_haval_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_haval_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_cupra_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_cupra_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_cupra_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_cupra_medal';
update public.products set colors = '[{"id":"c_black_carbon","name_en":"Black Carbon","name_ar":"أسود كربوني","hex":"#232326","enabled":true},{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_gunmetal","name_en":"Gunmetal","name_ar":"رمادي مدفعي","hex":"#4A4E55","enabled":true}]'::jsonb where id = 'p_skoda_case1';
update public.products set colors = '[{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true},{"id":"c_chestnut_brown","name_en":"Chestnut Brown","name_ar":"بني كستنائي","hex":"#7B4A2D","enabled":true},{"id":"c_midnight_blue","name_en":"Midnight Blue","name_ar":"أزرق منتصف الليل","hex":"#1F2A44","enabled":true}]'::jsonb where id = 'p_skoda_case2';
update public.products set colors = '[{"id":"c_champagne_gold","name_en":"Champagne Gold","name_ar":"ذهبي شمباني","hex":"#C8A15A","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true},{"id":"c_black","name_en":"Black","name_ar":"أسود","hex":"#1D1D1F","enabled":true}]'::jsonb where id = 'p_skoda_holder';
update public.products set colors = '[{"id":"c_gold","name_en":"Gold","name_ar":"ذهبي","hex":"#D4AF37","enabled":true},{"id":"c_silver","name_en":"Silver","name_ar":"فضي","hex":"#C9CCD1","enabled":true}]'::jsonb where id = 'p_skoda_medal';

-- ---- dictionary keys for the color UI (merge, never overwrite) ------------
update public.settings
set value = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(value, '{dict,en,color}', to_jsonb('Color'::text), true), '{dict,ar,color}', to_jsonb('اللون'::text), true), '{dict,en,colors}', to_jsonb('Colors'::text), true), '{dict,ar,colors}', to_jsonb('الألوان'::text), true), '{dict,en,select_color}', to_jsonb('SELECT YOUR COLOR'::text), true), '{dict,ar,select_color}', to_jsonb('اختر اللون'::text), true), '{dict,en,color_required}', to_jsonb('Please choose a color first.'::text), true), '{dict,ar,color_required}', to_jsonb('يرجى اختيار اللون أولاً.'::text), true)
where key = 'languages';

-- ---- verification -----------------------------------------------------------
select count(*) as products_with_colors from public.products where colors is not null and colors <> '[]'::jsonb;
select value->'dict'->'en'->>'select_color' as en_select_color,
       value->'dict'->'ar'->>'select_color' as ar_select_color
from public.settings where key = 'languages';

commit;
